### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rrrnld** [g-div/berlin-opengeo#3]
I would like to re-use some of the code (and publish my changes / improvements); can you clarify which license it's published under?  
Thanks! :)

**Comment by g-div** [comment]
Hey Arne! 
I hope the MIT License is permissive enough for your purposes. You should know that the data are from [datenjournalist.de](http://datenjournalist.de/strassen-und-hausnummern-in-berlin-mit-geokoordinaten-als-open-data/), where it is explained that:
```
Die Lizenzfrage ist noch nicht eindeutig geklärt, es sollte auf jeden Fall die Quelle angegeben werden. Auf daten.berlin.de heißt es: „Die bisherigen vielschichtigen Nutzungsbedingungen werden aufgehoben und durch neue einheitliche Nutzungsbedingungen, die eine kostenfreie kommerzielle und nicht-kommerzielle Nutzung erlauben, ersetzt.“ 
```

The API uses [apibox](https://github.com/g-div/apibox), an older project I'm not maintaining anymore, but it should work with few adjustments. Let me know if I can help you further.
